name: Welcome New Contributors


on:
  pull_request_target:
    types: [opened]


    jobs:
      greet:
        runs-on: ubuntu-latest
        steps:
          - name: Comment a welcome message
          - uses: actions/checkout@v4
            run: echo "Hello github actions !"
